/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as OverTimeRouteImport } from './routes/over-time'
import { Route as EmailPreviewRouteImport } from './routes/email-preview'
import { Route as IndexRouteImport } from './routes/index'

const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const OverTimeRoute = OverTimeRouteImport.update({
  id: '/over-time',
  path: '/over-time',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailPreviewRoute = EmailPreviewRouteImport.update({
  id: '/email-preview',
  path: '/email-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-preview': typeof EmailPreviewRoute
  '/over-time': typeof OverTimeRoute
  '/routes': typeof RoutesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-preview': typeof EmailPreviewRoute
  '/over-time': typeof OverTimeRoute
  '/routes': typeof RoutesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email-preview': typeof EmailPreviewRoute
  '/over-time': typeof OverTimeRoute
  '/routes': typeof RoutesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/email-preview' | '/over-time' | '/routes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/email-preview' | '/over-time' | '/routes'
  id: '__root__' | '/' | '/email-preview' | '/over-time' | '/routes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailPreviewRoute: typeof EmailPreviewRoute
  OverTimeRoute: typeof OverTimeRoute
  RoutesRoute: typeof RoutesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-time': {
      id: '/over-time'
      path: '/over-time'
      fullPath: '/over-time'
      preLoaderRoute: typeof OverTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-preview': {
      id: '/email-preview'
      path: '/email-preview'
      fullPath: '/email-preview'
      preLoaderRoute: typeof EmailPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailPreviewRoute: EmailPreviewRoute,
  OverTimeRoute: OverTimeRoute,
  RoutesRoute: RoutesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
